name: golang-pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - uses: actions/checkout@v4

      - name: Запуск Юнит Тестов
        run: GOOS=linux GOARCH=amd64 go test

      - name: Статический анализ кода
        run: |
          go vet ./...

  deploy:
    name: Отправка образа Docker в Docker Hub
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Клонирование в раннер
        uses: actions/checkout@v4

      - name: Настройка сборщика Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Аутентификация в реестре контейнеров
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Извлечение метаданных (тегов, меток) для Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: gecosdocker/sprint12-cicd

      - name: Сборка и отправка Docker Inage
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}